'From Cuis7.1 [latest update: #6526] on 24 July 2024 at 12:44:53 pm'!
'Description I supply collected additional Widgets and Widget Components
not supplied in the base system Morphic-Widgets category.'!
!provides: 'UI-Components' 1 6!
!requires: 'UI-DragAndDrop' 1 1 nil!
!requires: 'UI-Entry' 1 50 nil!
!requires: 'UI-Click-Select' 1 57 nil!
!requires: 'UI-Panel' 1 102 nil!
!requires: 'UI-Widgets' 1 33 nil!
!requires: 'UI-Core' 1 12 nil!
SystemOrganization addCategory: #'UI-Components'!


