'From Cuis7.1 [latest update: #6523] on 20 July 2024 at 9:58:44 pm'!
'Description I supply collected additional Widgets and Widget Components
not supplied in the base system Morphic-Widgets category.'!
!provides: 'UI-Components' 1 5!
!requires: 'Cuis-Base' 60 5032 nil!
!requires: 'UI-DragAndDrop' 1 0 nil!
!requires: 'UI-Entry' 1 3 nil!
!requires: 'UI-Click-Select' 1 1 nil!
!requires: 'UI-Panel' 1 5 nil!
!requires: 'UI-Widgets' 1 0 nil!
!requires: 'UI-Color-Panel' 1 22 nil!
SystemOrganization addCategory: #'UI-Components'!


