'From Cuis 6.0 [latest update: #5032] on 4 January 2022 at 12:18:07 pm'!
'Description I supply collected additional Widgets and Widget Components
not supplied in the base system Morphic-Widgets category.'!
!provides: 'UI-Components' 1 4!
!requires: 'Cuis-Base' 60 5032 nil!
!requires: 'UI-DragAndDrop' 1 0 nil!
!requires: 'UI-Palette' 1 5 nil!
!requires: 'UI-Shapes' 1 2 nil!
!requires: 'UI-Entry' 1 3 nil!
!requires: 'UI-Click-Select' 1 1 nil!
!requires: 'UI-Panel' 1 5 nil!
!requires: 'UI-Widgets' 1 0 nil!
SystemOrganization addCategory: 'UI-Components'!


