'From Cuis 6.0 [latest update: #5057] on 2 February 2022 at 12:03:28 pm'!
'Description Users of various added Widgets'!
!provides: 'UI-Tools' 1 13!
!requires: 'UI-Components' 1 4 nil!
!requires: 'UI-Shapes' 1 12 nil!
!requires: 'UI-Color-Panel' 1 3 nil!
!requires: 'UI-MetaProperties' 1 102 nil!
!requires: 'UI-Layout-Panel' 1 8 nil!
!requires: 'UI-Palette' 1 10 nil!
SystemOrganization addCategory: 'UI-Tools'!


